SELECT TOP 2000 *
FROM claimtransaction_clean

SELECT
	ID AS CLAIMTRANSACTION_ID,
	CLAIMID AS CLAIM_ID,
	CHARGEID AS CHARGED_ID,
	PATIENTID AS PATIENT_ID,
	TYPE,
	METHOD,
	FROMDATE,
	TODATE,
	PROCEDURECODE as PROCEDURE_CODE,
	DIAGNOSISREF1,
    DIAGNOSISREF2,
    DIAGNOSISREF3,
    DIAGNOSISREF4,
    AMOUNT,                       -- Total billed amount (null for some rows)
    UNITAMOUNT,
    PAYMENTS,
    ADJUSTMENTS,
    TRANSFERS,
    OUTSTANDING,
    PLACEOFSERVICE,
	UNITS,
	DEPARTMENTID AS DEPARTMENT_ID,
	NOTES,
	TRANSFERTYPE,
	APPOINTMENTID AS APPOINTMENT_ID,
	PATIENTINSURANCEID AS PATIENTINSURANCE_ID
INTO
	claimtransaction_clean
FROM
	claims_transactions

--idividual billing report by patient id
SELECT PATIENT_ID,
       SUM(CASE WHEN TYPE = 'CHARGE' THEN AMOUNT ELSE 0 END) AS total_charged,
       SUM(PAYMENTS) AS total_paid,
       SUM(OUTSTANDING) AS current_balance
FROM claimtransaction_clean
GROUP BY PATIENT_ID


-- Update NULL
UPDATE 
	claimtransaction_clean
SET
	METHOD = ISNULL(METHOD, 'No Method'),
	DIAGNOSISREF2 = ISNULL(DIAGNOSISREF2, 2),
	DIAGNOSISREF3 = ISNULL(DIAGNOSISREF3, 3),
	DIAGNOSISREF4 = ISNULL(DIAGNOSISREF4, 4),
	AMOUNT = ISNULL(AMOUNT, 0),
	TRANSFERS = ISNULL(TRANSFERS, 0),
	TRANSFERTYPE = ISNULL(TRANSFERTYPE, 'None')
WHERE
	METHOD IS NULL OR
	DIAGNOSISREF2 IS NULL OR
	DIAGNOSISREF3 IS NULL OR
	DIAGNOSISREF4 IS NULL OR
	AMOUNT IS NULL OR
	TRANSFERS IS NULL OR
	TRANSFERTYPE IS NULL



--
SELECT 
	DEPARTMENT_ID,
	SUM(CASE WHEN TYPE = 'CHARGE' THEN AMOUNT ELSE 0 END) AS department_charges,
    SUM(PAYMENTS) AS department_payments
FROM 
	claimtransaction_clean
GROUP BY
	DEPARTMENT_ID



-- claims by time (for monthly trend)
SELECT 
	DATETRUNC(MONTH, FROMDATE) AS service_month,
	COUNT(DISTINCT CLAIM_ID) AS num_claims,
    SUM(AMOUNT) AS monthly_charges
FROM 
	claimtransaction_clean
WHERE 
	TYPE = 'CHARGE'
GROUP BY 
	DATETRUNC(MONTH, FROMDATE)
ORDER BY 
	service_month

	