SELECT* FROM claim_clean

SELECT
	ID AS CLAIM_ID,
	PATIENTID AS PATIENT_ID,
	PROVIDERID AS PROVIDER_ID,
	PRIMARYPATIENTINSURANCEID,
	SECONDARYPATIENTINSURANCEID,
	DEPARTMENTID,
	PATIENTDEPARTMENTID,
	DIAGNOSIS1,
	DIAGNOSIS2,
	DIAGNOSIS3,
	DIAGNOSIS4,
	DIAGNOSIS5,
	DIAGNOSIS6,
	DIAGNOSIS7,
	DIAGNOSIS8,
	APPOINTMENTID,
	CURRENTILLNESSDATE,
	SERVICEDATE,
	SUPERVISINGPROVIDERID,
	STATUS1,
	STATUS2,
	STATUSP,
	LASTBILLEDDATE1,
	LASTBILLEDDATE2,
	LASTBILLEDDATEP
INTO 
	claim_clean
FROM 
	claims


--uppdate null
UPDATE 
	claim_clean
SET 
	PRIMARYPATIENTINSURANCEID = ISNULL(PRIMARYPATIENTINSURANCEID, 'No Id'),
	SECONDARYPATIENTINSURANCEID = ISNULL(SECONDARYPATIENTINSURANCEID, 'No Id'),
	DIAGNOSIS2 = ISNULL(DIAGNOSIS2, 'None'),
	DIAGNOSIS3 = ISNULL(DIAGNOSIS3, 'None'),
	DIAGNOSIS4 = ISNULL(DIAGNOSIS4, 'None'),
	DIAGNOSIS5 = ISNULL(DIAGNOSIS5, 'None'),
	DIAGNOSIS6 = ISNULL(DIAGNOSIS6, 'None'),
	DIAGNOSIS7 = ISNULL(DIAGNOSIS7, 'None'),
	DIAGNOSIS8 = ISNULL(DIAGNOSIS8, 'None'),
	STATUS2 = ISNULL(STATUS2, 'No Status'),
	LASTBILLEDDATE2 = COALESCE(LASTBILLEDDATE2, LASTBILLEDDATEP) ---since it is same date
WHERE 
	PRIMARYPATIENTINSURANCEID IS NULL OR 
	SECONDARYPATIENTINSURANCEID IS NULL OR 
	DIAGNOSIS2 IS NULL OR 
	DIAGNOSIS3 IS NULL OR 
	DIAGNOSIS4 IS NULL OR 
	DIAGNOSIS5 IS NULL OR 
	DIAGNOSIS6 IS NULL OR 
	DIAGNOSIS7 IS NULL OR 
	DIAGNOSIS8 IS NULL OR 
	STATUS2 IS NULL OR 
	LASTBILLEDDATE2 IS NULL;


--first and last billed patient
SELECT 
  PATIENT_ID,
  MIN(LASTBILLEDDATE1) AS FirstBilledDate,
  MAX(LASTBILLEDDATE1) AS LastBilledDate
FROM 
	claim_clean
GROUP BY 
	PATIENT_ID



--status summary of claims
SELECT 
  STATUS1,
  COUNT(*) AS CountByStatus
FROM 
	claim_clean
GROUP BY 
	STATUS1